##system environments
server.port: 9093
#在resource目录下添加processes文件夹，并且文件夹不能为空 
#spring.activiti.check-process-definitions: false

## Activiti DB
workflow.jdbc:
  type: mysql
  driverClassName: com.mysql.jdbc.Driver
  jdbcUrl: jdbc:mysql://127.0.0.1:3306/my-workflow?zeroDateTimeBehavior=convertToNull&amp;useUnicode=true&amp;characterEncoding=UTF-8
  username: root
  password: root
  # 连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
  maximumPoolSize: 100
  # 连接池中最小空闲连接数据
  minimumIdle: 1
  # 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒
  maxLifetime: 2000000
  # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 缺省:30秒
  connectionTimeout: 30000
  # 一个连接idle状态的最大时长（毫秒），超时则被释放（retired），缺省:10分钟
  idleTimeout: 30000
  defaultAutoCommit: false
  connectionTestQuery: SELECT 1 